"""Quellennachweis-Erweiterung, Kontaktwege, Zustaendigkeits-Staging

Revision ID: 30bb4888018f
Revises: 8bf5a88f4024
Create Date: 2026-09-26 00:22:01.109874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bb4888018f'
down_revision: Union[str, None] = '8bf5a88f4024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_contact_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('authority_id', sa.String(length=50), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('request_type_id', sa.String(length=50), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.authority_id'], ),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.request_type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authority_contact_channels', schema=None) as batch_op:
        batch_op.create_index('idx_contact_channel_authority', ['authority_id'], unique=False)
        batch_op.create_index('idx_contact_channel_type', ['channel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_authority_contact_channels_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_authority_contact_channels_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authority_contact_channels_request_type_id'), ['request_type_id'], unique=False)

    op.create_table('jurisdiction_staging_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('batch_label', sa.String(length=255), nullable=True),
    sa.Column('request_type_id', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('ags', sa.String(length=12), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('matching_level', sa.String(length=50), nullable=True),
    sa.Column('proposed_authority_id', sa.String(length=50), nullable=True),
    sa.Column('proposed_authority_name', sa.String(length=255), nullable=True),
    sa.Column('proposed_authority_city', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_license', sa.String(length=255), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_type', sa.String(length=30), nullable=False),
    sa.Column('conflicts_with_jurisdiction_id', sa.String(length=100), nullable=True),
    sa.Column('conflict_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resulting_jurisdiction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conflicts_with_jurisdiction_id'], ['jurisdictions.jurisdiction_id'], ),
    sa.ForeignKeyConstraint(['proposed_authority_id'], ['authorities.authority_id'], ),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.request_type_id'], ),
    sa.ForeignKeyConstraint(['resulting_jurisdiction_id'], ['jurisdictions.jurisdiction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jurisdiction_staging_entries', schema=None) as batch_op:
        batch_op.create_index('idx_staging_ags_request_type', ['ags', 'request_type_id'], unique=False)
        batch_op.create_index('idx_staging_batch', ['batch_id'], unique=False)
        batch_op.create_index('idx_staging_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_staging_entries_ags'), ['ags'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_staging_entries_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_staging_entries_conflict_type'), ['conflict_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_staging_entries_request_type_id'), ['request_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_staging_entries_status'), ['status'], unique=False)

    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_license', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_retrieved_at', sa.DateTime(), nullable=True))
        # server_default ist hier PFLICHT, nicht nur der ORM-seitige Python-
        # default auf dem Model: die 16.290 bestehenden Zeilen (Produktion
        # wie lokale Entwicklungs-DB) brauchen beim Hinzufügen einer NOT-
        # NULL-Spalte einen tatsächlichen DB-Wert, sonst schlägt das ALTER
        # TABLE fehl. "AUTO_IMPORTED" ist inhaltlich korrekt: keine der
        # bestehenden Regeln hat je last_verified_at/verified_by gesetzt
        # (siehe Auswertung im Abschlussbericht) - sie waren also nie
        # fachlich bestätigt, sondern ausschließlich automatisiert importiert.
        batch_op.add_column(sa.Column(
            'verification_status', sa.String(length=30), nullable=False,
            server_default='AUTO_IMPORTED',
        ))
        batch_op.create_index(batch_op.f('ix_jurisdictions_verification_status'), ['verification_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdictions_verification_status'))
        batch_op.drop_column('verification_status')
        batch_op.drop_column('source_retrieved_at')
        batch_op.drop_column('source_license')
        batch_op.drop_column('source_url')

    with op.batch_alter_table('jurisdiction_staging_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdiction_staging_entries_status'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_staging_entries_request_type_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_staging_entries_conflict_type'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_staging_entries_batch_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_staging_entries_ags'))
        batch_op.drop_index('idx_staging_status')
        batch_op.drop_index('idx_staging_batch')
        batch_op.drop_index('idx_staging_ags_request_type')

    op.drop_table('jurisdiction_staging_entries')
    with op.batch_alter_table('authority_contact_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authority_contact_channels_request_type_id'))
        batch_op.drop_index(batch_op.f('ix_authority_contact_channels_authority_id'))
        batch_op.drop_index(batch_op.f('ix_authority_contact_channels_active'))
        batch_op.drop_index('idx_contact_channel_type')
        batch_op.drop_index('idx_contact_channel_authority')

    op.drop_table('authority_contact_channels')
    # ### end Alembic commands ###
