"""Nutzer Account Status: Selbstregistrierung und Admin-Freigabe

Revision ID: 422bdc577ed0
Revises: 6b15f8ab3ccc
Create Date: 2026-10-01 15:12:58.758715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422bdc577ed0'
down_revision: Union[str, None] = '6b15f8ab3ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hinweis: Autogenerate hat erneut die bereits bekannte, VORBESTEHENDE und
    # unabhaengige Typ-Abweichung auf authorities.phone gefunden (siehe
    # Kommentar dazu in f37109f1de46 und 6b15f8ab3ccc) - weiterhin bewusst
    # NICHT Teil dieser Migration (ein Migrations-Commit = eine fachliche
    # Aenderung). Diese Migration betrifft ausschliesslich die users-Tabelle.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
