"""inbound_emails: message_id fuer Webhook-Idempotenz

Revision ID: 53a6c1a1c9f7
Revises: ab0d36228547
Create Date: 2026-09-25 21:14:16.119997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a6c1a1c9f7'
down_revision: Union[str, None] = 'ab0d36228547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(length=998), nullable=True))
        batch_op.create_index(batch_op.f('ix_inbound_emails_message_id'), ['message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_emails_message_id'))
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
