"""Jurisdiction.authority_id nullable fuer NOT_APPLICABLE-Status

Revision ID: 6b15f8ab3ccc
Revises: f37109f1de46
Create Date: 2026-09-29 17:08:32.621622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b15f8ab3ccc'
down_revision: Union[str, None] = 'f37109f1de46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hinweis: Autogenerate hat erneut eine VORBESTEHENDE, unabhaengige
    # Typ-Abweichung auf authorities.phone gefunden (siehe bereits
    # f37109f1de46's Kommentar dazu) - weiterhin bewusst NICHT Teil dieser
    # Migration (ein Migrations-Commit = eine fachliche Aenderung).
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.alter_column('authority_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.alter_column('authority_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
