"""buildings: source_system fuer stabile externe Referenzen

Revision ID: 8bf5a88f4024
Revises: 53a6c1a1c9f7
Create Date: 2026-09-25 21:48:40.866630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf5a88f4024'
down_revision: Union[str, None] = '53a6c1a1c9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_system', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_buildings_source_system'), ['source_system'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_source_system'))
        batch_op.drop_column('source_system')

    # ### end Alembic commands ###
