"""baseline: initial schema snapshot

Revision ID: ab0d36228547
Revises: 
Create Date: 2026-09-25 21:13:01.412804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0d36228547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_units',
    sa.Column('ags', sa.String(length=8), nullable=False),
    sa.Column('ags_land', sa.String(length=2), nullable=False),
    sa.Column('ags_regierungsbezirk', sa.String(length=1), nullable=True),
    sa.Column('ags_kreis', sa.String(length=5), nullable=False),
    sa.Column('ags_gemeinde', sa.String(length=3), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('county_name', sa.String(length=150), nullable=True),
    sa.Column('municipality_name', sa.String(length=150), nullable=False),
    sa.Column('municipality_type', sa.String(length=100), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('data_stand', sa.String(length=20), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ags')
    )
    with op.batch_alter_table('administrative_units', schema=None) as batch_op:
        batch_op.create_index('idx_admin_units_kreis', ['ags_kreis'], unique=False)
        batch_op.create_index('idx_admin_units_land', ['ags_land'], unique=False)
        batch_op.create_index('idx_admin_units_municipality_name', ['municipality_name'], unique=False)
        batch_op.create_index('idx_admin_units_postal_code', ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrative_units_ags_kreis'), ['ags_kreis'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrative_units_ags_land'), ['ags_land'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrative_units_county_name'), ['county_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrative_units_municipality_name'), ['municipality_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrative_units_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrative_units_state_name'), ['state_name'], unique=False)

    op.create_table('aktenzeichen_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorities',
    sa.Column('authority_id', sa.String(length=50), nullable=False),
    sa.Column('authority_type', sa.String(length=50), nullable=True),
    sa.Column('authority_name', sa.String(length=255), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('authority_id')
    )
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.create_index('idx_authorities_active', ['active'], unique=False)
        batch_op.create_index('idx_authorities_city_postal', ['city', 'postal_code'], unique=False)
        batch_op.create_index('idx_authorities_name', ['authority_name'], unique=False)
        batch_op.create_index('idx_authorities_state', ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_authority_name'), ['authority_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_state'), ['state'], unique=False)

    op.create_table('buildings',
    sa.Column('building_id', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('ags', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('internal_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index('idx_buildings_ags', ['ags'], unique=False)
        batch_op.create_index('idx_buildings_internal_ref', ['internal_reference'], unique=False)
        batch_op.create_index('idx_buildings_postal_city', ['postal_code', 'city'], unique=False)
        batch_op.create_index('idx_buildings_street', ['street'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_ags'), ['ags'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_internal_reference'), ['internal_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_buildings_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_street'), ['street'], unique=False)

    op.create_table('cases',
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('data_source_routing',
    sa.Column('routing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('routing_status', sa.String(length=50), nullable=True),
    sa.Column('primary_source_id', sa.String(length=100), nullable=True),
    sa.Column('fallback_source_id', sa.String(length=100), nullable=True),
    sa.Column('official_confirmation_required', sa.Boolean(), nullable=True),
    sa.Column('implementation_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('routing_id')
    )
    with op.batch_alter_table('data_source_routing', schema=None) as batch_op:
        batch_op.create_index('idx_data_source_routing_state_category', ['state_code', 'category'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_source_routing_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_source_routing_state_code'), ['state_code'], unique=False)

    op.create_table('data_sources',
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_authority', sa.String(length=255), nullable=True),
    sa.Column('access_type', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('endpoint_mode', sa.String(length=50), nullable=True),
    sa.Column('feature_collection_or_type', sa.Text(), nullable=True),
    sa.Column('preferred_output', sa.String(length=100), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('is_open_data', sa.Boolean(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('requires_fee', sa.Boolean(), nullable=True),
    sa.Column('data_status', sa.Text(), nullable=True),
    sa.Column('legal_status', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('fallback_source_id', sa.String(length=100), nullable=True),
    sa.Column('official_confirmation_required', sa.Boolean(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index('idx_data_sources_state_category', ['state_code', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_sources_state_code'), ['state_code'], unique=False)

    op.create_table('request_types',
    sa.Column('request_type_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_filename', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('request_type_id')
    )
    with op.batch_alter_table('request_types', schema=None) as batch_op:
        batch_op.create_index('idx_request_types_active', ['active'], unique=False)
        batch_op.create_index('idx_request_types_code', ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_types_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_types_code'), ['code'], unique=True)

    op.create_table('authority_locations',
    sa.Column('authority_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geocoded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.authority_id'], ),
    sa.PrimaryKeyConstraint('authority_id')
    )
    op.create_table('case_buildings',
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('building_id', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'building_id')
    )
    op.create_table('jurisdictions',
    sa.Column('jurisdiction_id', sa.String(length=100), nullable=False),
    sa.Column('request_type_id', sa.String(length=50), nullable=False),
    sa.Column('authority_id', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('ags', sa.String(length=12), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('matching_level', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.authority_id'], ),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.request_type_id'], ),
    sa.PrimaryKeyConstraint('jurisdiction_id')
    )
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.create_index('idx_jurisdiction_active', ['active'], unique=False)
        batch_op.create_index('idx_jurisdiction_ags', ['ags'], unique=False)
        batch_op.create_index('idx_jurisdiction_priority', ['priority'], unique=False)
        batch_op.create_index('idx_jurisdiction_request_type_ags', ['request_type_id', 'ags', 'priority'], unique=False)
        batch_op.create_index('idx_jurisdiction_request_type_district', ['request_type_id', 'district', 'priority'], unique=False)
        batch_op.create_index('idx_jurisdiction_request_type_municipality', ['request_type_id', 'municipality', 'priority'], unique=False)
        batch_op.create_index('idx_jurisdiction_request_type_state', ['request_type_id', 'state', 'priority'], unique=False)
        batch_op.create_index('idx_jurisdiction_request_type_street', ['request_type_id', 'street', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_ags'), ['ags'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_municipality'), ['municipality'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_request_type_id'), ['request_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_street'), ['street'], unique=False)

    op.create_table('requests',
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('building_id', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index('idx_requests_building', ['building_id'], unique=False)
        batch_op.create_index('idx_requests_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_requests_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)

    op.create_table('case_requests',
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'request_id')
    )
    op.create_table('request_items',
    sa.Column('request_item_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('request_type_id', sa.String(length=50), nullable=False),
    sa.Column('authority_id', sa.String(length=50), nullable=True),
    sa.Column('matching_level', sa.String(length=50), nullable=True),
    sa.Column('matching_status', sa.String(length=50), nullable=False),
    sa.Column('matching_confidence', sa.Float(), nullable=False),
    sa.Column('alternative_authorities', sa.Text(), nullable=True),
    sa.Column('manually_changed', sa.Boolean(), nullable=True),
    sa.Column('manual_change_reason', sa.Text(), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('document_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.authority_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.request_type_id'], ),
    sa.PrimaryKeyConstraint('request_item_id')
    )
    with op.batch_alter_table('request_items', schema=None) as batch_op:
        batch_op.create_index('idx_request_items_document_status', ['document_status'], unique=False)
        batch_op.create_index('idx_request_items_matching_status', ['matching_status'], unique=False)
        batch_op.create_index('idx_request_items_request', ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_document_status'), ['document_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_manually_changed'), ['manually_changed'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_matching_status'), ['matching_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_request_type_id'), ['request_type_id'], unique=False)

    op.create_table('request_sequences',
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('inbound_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('matched_request_item_id', sa.String(length=100), nullable=True),
    sa.Column('auto_matched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_request_item_id'], ['request_items.request_item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_item_progress',
    sa.Column('request_item_id', sa.String(length=100), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('response_document', sa.LargeBinary(), nullable=True),
    sa.Column('response_document_filename', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_item_id'], ['request_items.request_item_id'], ),
    sa.PrimaryKeyConstraint('request_item_id')
    )
    op.create_table('request_item_references',
    sa.Column('request_item_id', sa.String(length=100), nullable=False),
    sa.Column('aktenzeichen', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_item_id'], ['request_items.request_item_id'], ),
    sa.PrimaryKeyConstraint('request_item_id')
    )
    op.create_table('inbound_email_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inbound_email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_email_id'], ['inbound_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbound_email_attachments')
    op.drop_table('request_item_references')
    op.drop_table('request_item_progress')
    op.drop_table('inbound_emails')
    op.drop_table('request_sequences')
    with op.batch_alter_table('request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_items_request_type_id'))
        batch_op.drop_index(batch_op.f('ix_request_items_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_items_matching_status'))
        batch_op.drop_index(batch_op.f('ix_request_items_manually_changed'))
        batch_op.drop_index(batch_op.f('ix_request_items_document_status'))
        batch_op.drop_index(batch_op.f('ix_request_items_authority_id'))
        batch_op.drop_index('idx_request_items_request')
        batch_op.drop_index('idx_request_items_matching_status')
        batch_op.drop_index('idx_request_items_document_status')

    op.drop_table('request_items')
    op.drop_table('case_requests')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_requests_building_id'))
        batch_op.drop_index('idx_requests_status')
        batch_op.drop_index('idx_requests_created_at')
        batch_op.drop_index('idx_requests_building')

    op.drop_table('requests')
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdictions_street'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_state'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_request_type_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_priority'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_postal_code'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_municipality'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_district'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_authority_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_ags'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_active'))
        batch_op.drop_index('idx_jurisdiction_request_type_street')
        batch_op.drop_index('idx_jurisdiction_request_type_state')
        batch_op.drop_index('idx_jurisdiction_request_type_municipality')
        batch_op.drop_index('idx_jurisdiction_request_type_district')
        batch_op.drop_index('idx_jurisdiction_request_type_ags')
        batch_op.drop_index('idx_jurisdiction_priority')
        batch_op.drop_index('idx_jurisdiction_ags')
        batch_op.drop_index('idx_jurisdiction_active')

    op.drop_table('jurisdictions')
    op.drop_table('case_buildings')
    op.drop_table('authority_locations')
    with op.batch_alter_table('request_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_types_code'))
        batch_op.drop_index(batch_op.f('ix_request_types_active'))
        batch_op.drop_index('idx_request_types_code')
        batch_op.drop_index('idx_request_types_active')

    op.drop_table('request_types')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_state_code'))
        batch_op.drop_index(batch_op.f('ix_data_sources_category'))
        batch_op.drop_index('idx_data_sources_state_category')

    op.drop_table('data_sources')
    with op.batch_alter_table('data_source_routing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_routing_state_code'))
        batch_op.drop_index(batch_op.f('ix_data_source_routing_category'))
        batch_op.drop_index('idx_data_source_routing_state_category')

    op.drop_table('data_source_routing')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))

    op.drop_table('cases')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_street'))
        batch_op.drop_index(batch_op.f('ix_buildings_postal_code'))
        batch_op.drop_index(batch_op.f('ix_buildings_internal_reference'))
        batch_op.drop_index(batch_op.f('ix_buildings_city'))
        batch_op.drop_index(batch_op.f('ix_buildings_ags'))
        batch_op.drop_index('idx_buildings_street')
        batch_op.drop_index('idx_buildings_postal_city')
        batch_op.drop_index('idx_buildings_internal_ref')
        batch_op.drop_index('idx_buildings_ags')

    op.drop_table('buildings')
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorities_state'))
        batch_op.drop_index(batch_op.f('ix_authorities_postal_code'))
        batch_op.drop_index(batch_op.f('ix_authorities_city'))
        batch_op.drop_index(batch_op.f('ix_authorities_authority_name'))
        batch_op.drop_index(batch_op.f('ix_authorities_active'))
        batch_op.drop_index('idx_authorities_state')
        batch_op.drop_index('idx_authorities_name')
        batch_op.drop_index('idx_authorities_city_postal')
        batch_op.drop_index('idx_authorities_active')

    op.drop_table('authorities')
    op.drop_table('app_settings')
    op.drop_table('aktenzeichen_sequences')
    with op.batch_alter_table('administrative_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrative_units_state_name'))
        batch_op.drop_index(batch_op.f('ix_administrative_units_postal_code'))
        batch_op.drop_index(batch_op.f('ix_administrative_units_municipality_name'))
        batch_op.drop_index(batch_op.f('ix_administrative_units_county_name'))
        batch_op.drop_index(batch_op.f('ix_administrative_units_ags_land'))
        batch_op.drop_index(batch_op.f('ix_administrative_units_ags_kreis'))
        batch_op.drop_index('idx_admin_units_postal_code')
        batch_op.drop_index('idx_admin_units_municipality_name')
        batch_op.drop_index('idx_admin_units_land')
        batch_op.drop_index('idx_admin_units_kreis')

    op.drop_table('administrative_units')
    # ### end Alembic commands ###
