"""Nutzer-Konten (users-Tabelle)

Revision ID: f37109f1de46
Revises: 30bb4888018f
Create Date: 2026-09-29 01:03:46.895023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37109f1de46'
down_revision: Union[str, None] = '30bb4888018f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hinweis: Autogenerate hat zusaetzlich eine VORBESTEHENDE, mit dieser
    # Aenderung unzusammenhaengende Typ-Abweichung auf authorities.phone
    # gefunden (Modell sagt String(100), DB hat noch VARCHAR(20) aus der
    # Baseline-Migration) - das ist absichtlich NICHT Teil dieser Migration
    # (ein Migrations-Commit = eine fachliche Aenderung), sondern bleibt fuer
    # eine separate, eigene Korrektur vorgemerkt.
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('function', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_active', ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_active'))
        batch_op.drop_index('idx_users_active')

    op.drop_table('users')
    # ### end Alembic commands ###
